package buildkit_test

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"strings"
	"testing"
	"time"

	"cubeship/internal/platform/buildkit"
	"cubeship/internal/platform/dockerx"
)

// The frontend reads a plan this binary generated, and a plan is a
// versioned document. A frontend reading one it does not understand is a
// build that fails for no reason anybody can see, so the two versions
// have to be the same one.
func TestTheFrontendMatchesTheRailpackWeBuildPlansWith(t *testing.T) {
	out, err := exec.Command("go", "list", "-m", "github.com/railwayapp/railpack").Output()
	if err != nil {
		t.Fatalf("read the railpack version from go.mod: %v", err)
	}
	// "github.com/railwayapp/railpack v0.39.0"
	fields := strings.Fields(strings.TrimSpace(string(out)))
	if len(fields) != 2 {
		t.Fatalf("unexpected `go list -m` output: %q", out)
	}
	want := "ghcr.io/railwayapp/railpack-frontend:" + fields[1]
	if buildkit.FrontendImage != want {
		t.Errorf("the frontend is %q but plans are generated by %s — bump railpackVersion",
			buildkit.FrontendImage, fields[1])
	}
}

// The whole point of Railpack: a repository with no Dockerfile in it,
// and Cubeship works out the build.
func TestPlanRepositoryUnderstandsARepositoryWithNoDockerfile(t *testing.T) {
	dir := source(t, map[string]string{
		"package.json": `{"name":"demo","version":"1.0.0","scripts":{"start":"node index.js"}}`,
		"index.js":     `console.log("hello")`,
	})

	plan, providers, err := buildkit.PlanRepository(dir, map[string]string{})
	if err != nil {
		t.Fatalf("PlanRepository: %v", err)
	}
	if len(providers) == 0 {
		t.Fatal("nothing was detected in a repository with a package.json")
	}
	if !contains(providers, "node") {
		t.Errorf("detected %v, want node among them", providers)
	}

	// The plan has to be the document the frontend reads, not any JSON.
	var decoded map[string]any
	if err := json.Unmarshal(plan, &decoded); err != nil {
		t.Fatalf("the plan is not valid JSON: %v", err)
	}
	if _, ok := decoded["steps"]; !ok {
		t.Errorf("the plan has no steps: %s", plan)
	}
}

// A repository Railpack cannot make sense of must fail with what it
// said. "Planning failed" on its own leaves nothing to act on.
func TestPlanRepositoryExplainsWhatItCouldNotDo(t *testing.T) {
	dir := source(t, map[string]string{"notes.txt": "nothing to build here"})

	_, _, err := buildkit.PlanRepository(dir, map[string]string{})
	if err == nil {
		t.Fatal("a repository with no application in it was planned successfully")
	}
	if !strings.Contains(err.Error(), "railpack") {
		t.Errorf("the error does not say what refused: %v", err)
	}
}

// The environment reaches the plan, because Railpack reads it for the
// versions and commands a project pins — so a build's result depends on
// it and not only on the code.
func TestTheEnvironmentReachesThePlan(t *testing.T) {
	files := map[string]string{
		"package.json": `{"name":"demo","version":"1.0.0","scripts":{"start":"node index.js"}}`,
		"index.js":     `console.log("hello")`,
	}

	plain, _, err := buildkit.PlanRepository(source(t, files), map[string]string{})
	if err != nil {
		t.Fatal(err)
	}
	pinned, _, err := buildkit.PlanRepository(source(t, files), map[string]string{
		"RAILPACK_NODE_VERSION": "20",
	})
	if err != nil {
		t.Fatal(err)
	}
	if bytes.Equal(plain, pinned) {
		t.Error("pinning a Node version changed nothing in the plan")
	}
	if !strings.Contains(string(pinned), "20") {
		t.Errorf("the pinned version is not in the plan:\n%s", pinned)
	}
}

// End to end: a repository with no Dockerfile becomes an image that
// runs.
func TestBuildWithRailpack(t *testing.T) {
	docker, err := dockerx.New()
	if err != nil {
		t.Fatal(err)
	}
	b := buildkit.New(buildkitd(t), docker)

	dir := source(t, map[string]string{
		"package.json": `{"name":"demo","version":"1.0.0","scripts":{"start":"node index.js"}}`,
		"index.js":     `console.log("built by railpack")`,
	})

	plan, _, err := buildkit.PlanRepository(dir, map[string]string{})
	if err != nil {
		t.Fatalf("PlanRepository: %v", err)
	}
	planDir, cleanup, err := buildkit.WritePlan(plan)
	if err != nil {
		t.Fatal(err)
	}
	defer cleanup()

	image := fmt.Sprintf("cubeship-test/railpack:%d", time.Now().UnixNano())
	t.Cleanup(func() { exec.Command("docker", "rmi", "-f", image).Run() })

	var logs bytes.Buffer
	if err := b.BuildPlanned(context.Background(), buildkit.PlannedRequest{
		ContextDir: dir, PlanDir: planDir, Image: image, CacheKey: "test",
	}, &logs); err != nil {
		t.Fatalf("BuildPlanned: %v\n%s", err, logs.String())
	}

	out, err := exec.Command("docker", "run", "--rm", image).CombinedOutput()
	if err != nil {
		t.Fatalf("run the built image: %v\n%s", err, out)
	}
	if !strings.Contains(string(out), "built by railpack") {
		t.Errorf("the built image printed %q", out)
	}
}

// Clone is what Railpack needs and a Dockerfile build does not: the
// source has to be on the daemon's disk to be read before it is built.
func TestCloneFetchesARef(t *testing.T) {
	repoURL := localRepoPath(t, map[string]string{"README.md": "hello"})

	dir, cleanup, err := buildkit.Clone(context.Background(), repoURL, "main", "")
	if err != nil {
		t.Fatalf("Clone: %v", err)
	}
	defer cleanup()

	data, err := os.ReadFile(dir + "/README.md")
	if err != nil {
		t.Fatalf("the clone is missing the file: %v", err)
	}
	if string(data) != "hello" {
		t.Errorf("cloned %q", data)
	}
}

// A ref that does not exist has to say so, rather than quietly building
// whatever the default branch happens to be.
func TestCloneRefusesAnUnknownRef(t *testing.T) {
	repoURL := localRepoPath(t, map[string]string{"README.md": "hello"})

	_, _, err := buildkit.Clone(context.Background(), repoURL, "no-such-branch", "")
	if err == nil {
		t.Fatal("an unknown ref was cloned anyway")
	}
}

func contains(haystack []string, needle string) bool {
	for _, s := range haystack {
		if strings.Contains(strings.ToLower(s), needle) {
			return true
		}
	}
	return false
}
