package buildkit_test

import (
	"context"
	"os"
	"os/exec"
	"strings"
	"testing"

	"cubeship/internal/platform/buildkit"
)

// The frontend reads a plan this binary generated, and a plan is a
// versioned document. A frontend reading one it does not understand is a
// build that fails for no reason anybody can see, so the two versions
// have to be the same one.
func TestTheFrontendMatchesTheRailpackWeBuildPlansWith(t *testing.T) {
	out, err := exec.Command("go", "list", "-m", "github.com/railwayapp/railpack").Output()
	if err != nil {
		t.Fatalf("read the railpack version from go.mod: %v", err)
	}
	// "github.com/railwayapp/railpack v0.39.0"
	fields := strings.Fields(strings.TrimSpace(string(out)))
	if len(fields) != 2 {
		t.Fatalf("unexpected `go list -m` output: %q", out)
	}
	want := "ghcr.io/railwayapp/railpack-frontend:" + fields[1]
	if buildkit.FrontendImage != want {
		t.Errorf("the frontend is %q but plans are generated by %s — bump railpackVersion",
			buildkit.FrontendImage, fields[1])
	}
}

// Clone is what Railpack needs and a Dockerfile build does not: the
// source has to be on the daemon's disk to be read before it is built.
func TestCloneFetchesARef(t *testing.T) {
	repoURL := localRepoPath(t, map[string]string{"README.md": "hello"})

	dir, cleanup, err := buildkit.Clone(context.Background(), repoURL, "main", "")
	if err != nil {
		t.Fatalf("Clone: %v", err)
	}
	defer cleanup()

	data, err := os.ReadFile(dir + "/README.md")
	if err != nil {
		t.Fatalf("the clone is missing the file: %v", err)
	}
	if string(data) != "hello" {
		t.Errorf("cloned %q", data)
	}
}

// A ref that does not exist has to say so, rather than quietly building
// whatever the default branch happens to be.
func TestCloneRefusesAnUnknownRef(t *testing.T) {
	repoURL := localRepoPath(t, map[string]string{"README.md": "hello"})

	_, _, err := buildkit.Clone(context.Background(), repoURL, "no-such-branch", "")
	if err == nil {
		t.Fatal("an unknown ref was cloned anyway")
	}
}
