package datastore

import (
	"context"
	"fmt"

	"cubeship/internal/user"

	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// The tools deliberately stop short of two things.
//
// **No tool reads a password, and no tool sets one.** A datastore's
// password is generated by the daemon and reaches the app that needs it
// through its environment — so an agent can provision a database, wire
// an app to it and never hold the credential at any point. That is the
// same line internal/extregistry draws by having no tools at all, drawn
// where it still leaves the useful half: the reason not to expose a
// registry login is that it would pass through a model's context, and
// nothing here has to.
//
// **No tool exposes a datastore on a host port.** Publishing a database
// to the internet is an operator's decision about a firewall they own,
// and the API and the dashboard are where somebody makes it deliberately.
type Tools struct {
	svc    *Service
	caller *user.User
}

func NewTools(svc *Service, caller *user.User) *Tools {
	return &Tools{svc: svc, caller: caller}
}

func (t *Tools) Register(srv *mcp.Server) {
	mcp.AddTool(srv, &mcp.Tool{
		Name:        "create_datastore",
		Description: "Provision a managed database on this instance. It belongs to the instance, not to a project — one database can serve apps in several. It comes up with a generated password, which is never returned: attach an app to it and the app receives the connection string as environment variables. Requires the admin role.",
	}, t.create)
	mcp.AddTool(srv, &mcp.Tool{
		Name:        "list_datastores",
		Description: "List every managed database on this instance: which engine and version each runs, whether it is up, and which apps are attached to it.",
	}, t.list)
	mcp.AddTool(srv, &mcp.Tool{
		Name:        "get_datastore",
		Description: "Get one managed database by reference: its engine, version, status, the address apps reach it at, and what each attached app receives. Passwords are not reported.",
	}, t.get)
	mcp.AddTool(srv, &mcp.Tool{
		Name:        "list_datastore_engines",
		Description: "List the database engines this Cubeship release can run and the versions it offers for each. Call this before create_datastore rather than guessing a version.",
	}, t.engines)
	mcp.AddTool(srv, &mcp.Tool{
		Name:        "attach_datastore",
		Description: "Wire an app to a database: the app's container is given DATABASE_URL and its parts from its next deploy onwards. The app is named by its full reference, project/environment/name, and may be in any project. Use a prefix like \"ANALYTICS_\" when one app needs a second database. Requires the admin role.",
	}, t.attach)
	mcp.AddTool(srv, &mcp.Tool{
		Name:        "detach_datastore",
		Description: "Unwire an app from a database. Its container keeps the variables it was created with until it is deployed again, so this is not how you cut an app off in a hurry. Requires the admin role.",
	}, t.detach)
	mcp.AddTool(srv, &mcp.Tool{
		Name:        "delete_datastore",
		Description: "Delete a managed database, stop its container and remove its data from disk. This cannot be undone and there is no backup. Requires the admin role.",
	}, t.delete)
}

type createInput struct {
	Name        string `json:"name" jsonschema:"the database's name, unique on the instance: lowercase letters, digits and dashes. It is the container's name and is permanent"`
	Description string `json:"description,omitempty" jsonschema:"what this database is for, in a sentence"`
	Engine      string `json:"engine" jsonschema:"which server to run: postgres, mysql or mariadb. Call list_datastore_engines for what this release offers"`
	Version     string `json:"version,omitempty" jsonschema:"a version this release offers for that engine. Defaults to the newest. Permanent — a major version cannot be changed under an existing data directory"`
	Username    string `json:"username,omitempty" jsonschema:"the login to create. Defaults to \"cubeship\". MySQL and MariaDB will not accept \"root\""`
	Database    string `json:"database,omitempty" jsonschema:"the database to create inside the server. Defaults to the name with dashes turned into underscores"`
}

func (t *Tools) create(ctx context.Context, _ *mcp.CallToolRequest, in createInput) (*mcp.CallToolResult, Response, error) {
	created, err := t.svc.Create(ctx, t.caller, Spec{
		Slug: in.Name, Description: in.Description,
		Engine: Engine(in.Engine), Version: in.Version,
		Username: in.Username, Database: in.Database,
	})
	if err != nil {
		return nil, Response{}, err
	}
	// toResponse carries no password, which is the whole point — see
	// the note on Tools.
	return nil, toResponse(created, t.instance(ctx)), nil
}

// instance is what a response needs about the instance itself. The MCP
// surface reads it exactly where the HTTP one does.
func (t *Tools) instance(ctx context.Context) Instance {
	return Instance{Domain: t.svc.externalHost(ctx)}
}

type nameInput struct {
	Datastore string `json:"datastore" jsonschema:"the database's name on this instance"`
}

func (t *Tools) get(ctx context.Context, _ *mcp.CallToolRequest, in nameInput) (*mcp.CallToolResult, Response, error) {
	d, err := t.svc.Resolve(ctx, t.caller, in.Datastore, user.RoleMember)
	if err != nil {
		return nil, Response{}, err
	}
	return nil, toResponse(d, t.instance(ctx)), nil
}

func (t *Tools) list(ctx context.Context, _ *mcp.CallToolRequest, _ struct{}) (*mcp.CallToolResult, []Response, error) {
	all, err := t.svc.List(ctx, t.caller)
	if err != nil {
		return nil, nil, err
	}
	return nil, toResponses(all, t.instance(ctx)), nil
}

func (t *Tools) engines(ctx context.Context, _ *mcp.CallToolRequest, _ struct{}) (*mcp.CallToolResult, []EngineResponse, error) {
	if err := user.Require(t.caller, user.RoleMember); err != nil {
		return nil, nil, err
	}
	return nil, engineResponses(), nil
}

type attachInput struct {
	Datastore string `json:"datastore" jsonschema:"the database's name on this instance"`
	App       string `json:"app" jsonschema:"the app's full reference: project/environment/name, or project/name for production"`
	Prefix    string `json:"prefix,omitempty" jsonschema:"what the injected variables are named under, e.g. \"ANALYTICS_\". Leave empty for DATABASE_URL. Uppercase, ending in an underscore"`
}

func (t *Tools) attach(ctx context.Context, _ *mcp.CallToolRequest, in attachInput) (*mcp.CallToolResult, Response, error) {
	d, err := t.svc.Attach(ctx, t.caller, in.Datastore, in.App, in.Prefix)
	if err != nil {
		return nil, Response{}, err
	}
	return nil, toResponse(d, t.instance(ctx)), nil
}

type detachInput struct {
	Datastore string `json:"datastore" jsonschema:"the database's name on this instance"`
	App       string `json:"app" jsonschema:"the app's full reference: project/environment/name"`
}

func (t *Tools) detach(ctx context.Context, _ *mcp.CallToolRequest, in detachInput) (*mcp.CallToolResult, Response, error) {
	d, err := t.svc.Detach(ctx, t.caller, in.Datastore, in.App)
	if err != nil {
		return nil, Response{}, err
	}
	return nil, toResponse(d, t.instance(ctx)), nil
}

func (t *Tools) delete(ctx context.Context, _ *mcp.CallToolRequest, in nameInput) (*mcp.CallToolResult, user.ActionResult, error) {
	if _, err := t.svc.Delete(ctx, t.caller, in.Datastore); err != nil {
		return nil, user.ActionResult{}, err
	}
	return nil, user.ActionResult{
		Message: fmt.Sprintf("deleted datastore %s and the data on disk behind it", in.Datastore),
	}, nil
}
