package datastore

import (
	"context"
	"fmt"

	"cubeship/internal/mcpx"
	"cubeship/internal/user"

	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// The tools deliberately stop short of two things.
//
// **No tool reads a password, and no tool sets one.** A datastore's
// password is generated by the daemon and reaches the app that needs it
// through its environment — so an agent can provision a database, wire
// an app to it and never hold the credential at any point. That is the
// same line internal/extregistry draws by having no tools at all, drawn
// where it still leaves the useful half: the reason not to expose a
// registry login is that it would pass through a model's context, and
// nothing here has to.
//
// **No tool exposes a datastore on a host port.** Publishing a database
// to the internet is an operator's decision about a firewall they own,
// and the API and the dashboard are where somebody makes it deliberately.
type Tools struct {
	svc    *Service
	caller *user.User
}

func NewTools(svc *Service, caller *user.User) *Tools {
	return &Tools{svc: svc, caller: caller}
}

func (t *Tools) Register(srv *mcp.Server) {
	mcp.AddTool(srv, &mcp.Tool{
		Name:        "create_datastore",
		Description: "Provision a managed database on this instance. It belongs to the instance, not to a project — one database can serve apps in several. It comes up with a generated password, which is never returned: attach an app to it and the app receives the connection string as environment variables. Extensions can also be added afterwards with add_datastore_extensions, and can never be removed. Requires the admin role.",
	}, t.create)
	mcp.AddTool(srv, &mcp.Tool{
		Name:        "list_datastores",
		Description: "List every managed database on this instance: which engine and version each runs, which Postgres extensions it was created with, whether it is up, and which apps are attached to it.",
	}, t.list)
	mcp.AddTool(srv, &mcp.Tool{
		Name:        "get_datastore",
		Description: "Get one managed database by reference: its engine, version, extensions, status, the address apps reach it at, and what each attached app receives. Passwords are not reported.",
	}, t.get)
	mcp.AddTool(srv, &mcp.Tool{
		Name:        "list_datastore_engines",
		Description: "List the database engines this Cubeship release can run, the versions it offers for each, and the Postgres extensions available at each version. Call this before create_datastore rather than guessing a version or an extension.",
	}, t.engines)
	mcp.AddTool(srv, &mcp.Tool{
		Name:        "add_datastore_extensions",
		Description: "Install Postgres extensions on a database that already exists — \"pgvector\", \"vectorchord\". Adds only: everything the database already has stays, and removing one is refused because the data may already depend on it. **The container is replaced to pick the new image up**, so the database is unreachable for a few seconds and comes back as \"provisioning\"; its data survives, being a host bind mount. Asking for what is already there does nothing. Requires the admin role.",
	}, t.addExtensions)
	mcp.AddTool(srv, &mcp.Tool{
		Name:        "attach_datastore",
		Description: "Wire an app to a database: the app's container is given DATABASE_URL and its parts — REDIS_URL for a Redis, MONGO_URL for a MongoDB — from its next deploy onwards. The app is named by its full reference, project/environment/name, and may be in any project. Use a prefix like \"ANALYTICS_\" when one app needs a second database of the same kind; a cache beside a database needs none, since the two name different variables. Requires the admin role.",
	}, t.attach)
	mcp.AddTool(srv, &mcp.Tool{
		Name:        "detach_datastore",
		Description: "Unwire an app from a database. Its container keeps the variables it was created with until it is deployed again, so this is not how you cut an app off in a hurry. Requires the admin role.",
	}, t.detach)
	mcp.AddTool(srv, &mcp.Tool{
		Name:        "delete_datastore",
		Description: "Delete a managed database, stop its container and remove its data from disk. This cannot be undone and there is no backup. Requires the admin role.",
	}, t.delete)
}

type createInput struct {
	Name        string   `json:"name" jsonschema:"the database's name, unique on the instance: lowercase letters, digits and dashes. It is the container's name and is permanent"`
	Description string   `json:"description,omitempty" jsonschema:"what this database is for, in a sentence"`
	Engine      string   `json:"engine" jsonschema:"which server to run: postgres, mysql or mariadb. Call list_datastore_engines for what this release offers"`
	Version     string   `json:"version,omitempty" jsonschema:"a version this release offers for that engine. Defaults to the newest. Permanent — a major version cannot be changed under an existing data directory"`
	Extensions  []string `json:"extensions,omitempty" jsonschema:"Postgres extensions to create the database with, by name: \"pgvector\", \"vectorchord\". More can be added later with add_datastore_extensions, but none can ever be removed. \"vectorchord\" brings \"pgvector\" with it. Call list_datastore_engines for which versions offer which. Empty for every engine but postgres"`
	Username    string   `json:"username,omitempty" jsonschema:"the login to create. Defaults to \"cubeship\". MySQL and MariaDB will not accept \"root\""`
	Database    string   `json:"database,omitempty" jsonschema:"the database to create inside the server. Defaults to the name with dashes turned into underscores"`
}

func (t *Tools) create(ctx context.Context, _ *mcp.CallToolRequest, in createInput) (*mcp.CallToolResult, Response, error) {
	created, err := t.svc.Create(ctx, t.caller, Spec{
		Slug: in.Name, Description: in.Description,
		Engine: Engine(in.Engine), Version: in.Version, Extensions: in.Extensions,
		Username: in.Username, Database: in.Database,
	})
	if err != nil {
		return nil, Response{}, err
	}
	// toResponse carries no password, which is the whole point — see
	// the note on Tools.
	return nil, toResponse(created, t.instance(ctx)), nil
}

// instance is what a response needs about the instance itself. The MCP
// surface reads it exactly where the HTTP one does.
func (t *Tools) instance(ctx context.Context) Instance {
	return Instance{Domain: t.svc.externalHost(ctx)}
}

type nameInput struct {
	Datastore string `json:"datastore" jsonschema:"the database's name on this instance"`
}

func (t *Tools) get(ctx context.Context, _ *mcp.CallToolRequest, in nameInput) (*mcp.CallToolResult, Response, error) {
	d, err := t.svc.Resolve(ctx, t.caller, in.Datastore, user.LevelView)
	if err != nil {
		return nil, Response{}, err
	}
	return nil, toResponse(d, t.instance(ctx)), nil
}

func (t *Tools) list(ctx context.Context, _ *mcp.CallToolRequest, _ struct{}) (*mcp.CallToolResult, mcpx.List[Response], error) {
	all, err := t.svc.List(ctx, t.caller)
	if err != nil {
		return nil, mcpx.List[Response]{}, err
	}
	return nil, mcpx.Of(toResponses(all, t.instance(ctx))), nil
}

func (t *Tools) engines(ctx context.Context, _ *mcp.CallToolRequest, _ struct{}) (*mcp.CallToolResult, mcpx.List[EngineResponse], error) {
	if err := user.Require(t.caller, user.RoleMember); err != nil {
		return nil, mcpx.List[EngineResponse]{}, err
	}
	return nil, mcpx.Of(engineResponses()), nil
}

type extensionsInput struct {
	Datastore  string   `json:"datastore" jsonschema:"the database's name on this instance"`
	Extensions []string `json:"extensions" jsonschema:"the extensions to install, by name: \"pgvector\", \"vectorchord\". \"vectorchord\" brings \"pgvector\" with it. Call list_datastore_engines for which versions offer which"`
}

func (t *Tools) addExtensions(ctx context.Context, _ *mcp.CallToolRequest, in extensionsInput) (*mcp.CallToolResult, Response, error) {
	d, err := t.svc.AddExtensions(ctx, t.caller, in.Datastore, in.Extensions)
	if err != nil {
		return nil, Response{}, err
	}
	return nil, toResponse(d, t.instance(ctx)), nil
}

type attachInput struct {
	Datastore string `json:"datastore" jsonschema:"the database's name on this instance"`
	App       string `json:"app" jsonschema:"the app's full reference: project/environment/name, or project/name for production"`
	Prefix    string `json:"prefix,omitempty" jsonschema:"what the injected variables are named under, e.g. \"ANALYTICS_\". Leave empty for DATABASE_URL, REDIS_URL or MONGO_URL — whichever this engine writes. Only needed when two attachments would name the same variables. Uppercase, ending in an underscore"`
}

func (t *Tools) attach(ctx context.Context, _ *mcp.CallToolRequest, in attachInput) (*mcp.CallToolResult, Response, error) {
	d, err := t.svc.Attach(ctx, t.caller, in.Datastore, in.App, in.Prefix)
	if err != nil {
		return nil, Response{}, err
	}
	return nil, toResponse(d, t.instance(ctx)), nil
}

type detachInput struct {
	Datastore string `json:"datastore" jsonschema:"the database's name on this instance"`
	App       string `json:"app" jsonschema:"the app's full reference: project/environment/name"`
}

func (t *Tools) detach(ctx context.Context, _ *mcp.CallToolRequest, in detachInput) (*mcp.CallToolResult, Response, error) {
	d, err := t.svc.Detach(ctx, t.caller, in.Datastore, in.App)
	if err != nil {
		return nil, Response{}, err
	}
	return nil, toResponse(d, t.instance(ctx)), nil
}

func (t *Tools) delete(ctx context.Context, _ *mcp.CallToolRequest, in nameInput) (*mcp.CallToolResult, user.ActionResult, error) {
	if _, err := t.svc.Delete(ctx, t.caller, in.Datastore); err != nil {
		return nil, user.ActionResult{}, err
	}
	return nil, user.ActionResult{
		Message: fmt.Sprintf("deleted datastore %s and the data on disk behind it", in.Datastore),
	}, nil
}
